# Configuración compartida entre sistemas operativos

include current-theme.conf

font_family JetBrainsMono Nerd Font Mono
font_size 13.0
cursor_shape block
confirm_os_window_close 0
bold_font auto
italic_font auto
bold_italic_font auto

# Atajos comunes

# Incluye overrides locales si existen
include ./local.conf
