# Overrides para macOS
macos_thicken_font 0.2
# background_opacity 0.97
unicode_width auto
reflow yes
allow_width_override yes

map cmd+shift+enter launch --cwd=current
map cmd+{ toggle_layout stack
map cmd+, launch --type=overlay nvim ~/.config/kitty/kitty.conf

# Mover páneles
map cmd+shift+left move_window left
map cmd+shift+right move_window right
map cmd+shift+up move_window up
map cmd+shift+down move_window down

map cmd+. send_text all ~/.
map cmd+k combine : clear_terminal scrollback active : send_text normal \x0c
