# Overrides para macOS
font_family FiraMono Nerd Font Mono 
bold_font auto
italic_font auto
bold_italic_font auto

macos_thicken_font 0.2
background_opacity 0.97

map cmd+k combine : clear_terminal scrollback active : send_text normal \x0c
map cmd+shift+enter launch --cwd=current
map ctrl+alt+enter launch --cwd=current
map ctrl+b launch --type=overlay --tab-title='Git brachs' --stdin-source=@screen_scrollback /bin/sh -c "gb"
map cmd+{ toggle_layout stack
unicode_width auto
reflow yes
allow_width_override yes
map cmd+f launch --allow-remote-control kitty +kitten kitty_search/search.py @active-kitty-window-id
map cmd+. send_text all ~/.
map cmd+, launch --type=overlay nvim ~/.config/kitty/kitty.conf
map opt+, send_text all <
map opt+. send_text all >

map cmd+shift+left move_window left
map cmd+shift+right move_window right
map cmd+shift+up move_window up
map cmd+shift+down move_window down
