# Configuración compartida entre sistemas operativos

include current-theme.conf

font_size 12.0
cursor_shape block
confirm_os_window_close 0

# Atajos comunes
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab

# Incluye overrides locales si existen
include ./local.conf
